@wdk.on(events.NewMessage(incoming=True, pattern=r"\.pong"))
@hdk.on(events.NewMessage(incoming=True, pattern=r"\.pong"))
@sdk.on(events.NewMessage(incoming=True, pattern=r"\.pong"))
@adk.on(events.NewMessage(incoming=True, pattern=r"\.pong"))
@bdk.on(events.NewMessage(incoming=True, pattern=r"\.pong"))
@cdk.on(events.NewMessage(incoming=True, pattern=r"\.pong"))
@edk.on(events.NewMessage(incoming=True, pattern=r"\.pong"))
@ddk.on(events.NewMessage(incoming=True, pattern=r"\.pong"))
